SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_INFO AS A
JOIN ITEM_TREE AS B
ON B.PARENT_ITEM_ID = A.ITEM_ID
JOIN ITEM_INFO AS C
ON B.ITEM_ID = C.ITEM_ID
WHERE A.RARITY LIKE 'RARE'
ORDER BY ITEM_ID DESC;