SELECT DEV.ID, DEV.EMAIL, DEV.FIRST_NAME, DEV.LAST_NAME
FROM DEVELOPERS AS DEV
JOIN SKILLCODES AS SKILL_PY ON SKILL_PY.NAME = 'Python'
JOIN SKILLCODES AS SKILL_CS ON SKILL_CS.NAME = 'C#'
WHERE (DEV.SKILL_CODE & SKILL_PY.CODE) = SKILL_PY.CODE
OR (DEV.SKILL_CODE & SKILL_CS.CODE) = SKILL_CS.CODE
ORDER BY DEV.ID;